# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/huggingpolvo',
                'doc_host': 'https://lgvaz.github.io',
                'git_url': 'https://github.com/lgvaz/huggingpolvo',
                'lib_path': 'huggingpolvo'},
  'syms': {'huggingpolvo.core': {'huggingpolvo.core.foo': ('core.html#foo', 'huggingpolvo/core.py')}}}
